<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>GilbParser.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Sample\**\*.kt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
